### ISSUE TITLE
Doesn't build with aeson 1.2.2.0

### ISSUE THREAD

**Issue by felixonmars** [GetShopTV/swagger2#124]
I did the following in the Arch package to make it builds again:

```
sed -i 's/import Data.Aeson/import Data.Aeson hiding (constructorTagModifier)/' src/Data/Swagger/Internal/ParamSchema.hs
sed -i 's/import Data.Aeson/import Data.Aeson hiding (constructorTagModifier, unwrapUnaryRecords, fieldLabelModifier, allNullaryToStringTag)/' src/Data/Swagger/Internal/Schema.hs
```

The original errors:

```
[ 8 of 15] Compiling Data.Swagger.Internal.ParamSchema ( src/Data/Swagger/Internal/ParamSchema.hs, dist/build/Data/Swagger/Internal/ParamSchema.dyn_o )

src/Data/Swagger/Internal/ParamSchema.hs:298:21: error:
    Ambiguous occurrence ‘constructorTagModifier’
    It could refer to either ‘Data.Aeson.constructorTagModifier’,
                             imported from ‘Data.Aeson’ at src/Data/Swagger/Internal/ParamSchema.hs:25:1-17
                             (and originally defined in ‘aeson-1.2.2.0:Data.Aeson.Types.Internal’)
                          or ‘Data.Swagger.SchemaOptions.constructorTagModifier’,
                             imported from ‘Data.Swagger.SchemaOptions’ at src/Data/Swagger/Internal/ParamSchema.hs:46:1-33
                             (and originally defined
                                at src/Data/Swagger/SchemaOptions.hs:14:5-26)
    |
298 |       tag = toJSON (constructorTagModifier opts (conName (Proxy3 :: Proxy3 c f p)))
    |                     ^^^^^^^^^^^^^^^^^^^^^^
```

```
[10 of 15] Compiling Data.Swagger.Internal.Schema ( src/Data/Swagger/Internal/Schema.hs, dist/build/Data/Swagger/Internal/Schema.dyn_o )

src/Data/Swagger/Internal/Schema.hs:663:7: error:
    Ambiguous occurrence ‘unwrapUnaryRecords’
    It could refer to either ‘Data.Aeson.unwrapUnaryRecords’,
                             imported from ‘Data.Aeson’ at src/Data/Swagger/Internal/Schema.hs:35:1-17
                             (and originally defined in ‘aeson-1.2.2.0:Data.Aeson.Types.Internal’)
                          or ‘Data.Swagger.SchemaOptions.unwrapUnaryRecords’,
                             imported from ‘Data.Swagger.SchemaOptions’ at src/Data/Swagger/Internal/Schema.hs:67:1-33
                             (and originally defined
                                at src/Data/Swagger/SchemaOptions.hs:21:5-22)
    |
663 |     | unwrapUnaryRecords opts = fieldSchema
    |       ^^^^^^^^^^^^^^^^^^

src/Data/Swagger/Internal/Schema.hs:717:21: error:
    Ambiguous occurrence ‘fieldLabelModifier’
    It could refer to either ‘Data.Aeson.fieldLabelModifier’,
                             imported from ‘Data.Aeson’ at src/Data/Swagger/Internal/Schema.hs:35:1-17
                             (and originally defined in ‘aeson-1.2.2.0:Data.Aeson.Types.Internal’)
                          or ‘Data.Swagger.SchemaOptions.fieldLabelModifier’,
                             imported from ‘Data.Swagger.SchemaOptions’ at src/Data/Swagger/Internal/Schema.hs:67:1-33
                             (and originally defined
                                at src/Data/Swagger/SchemaOptions.hs:12:5-22)
    |
717 |     fname = T.pack (fieldLabelModifier opts (selName (Proxy3 :: Proxy3 s f p)))
    |                     ^^^^^^^^^^^^^^^^^^

src/Data/Swagger/Internal/Schema.hs:741:5: error:
    Ambiguous occurrence ‘allNullaryToStringTag’
    It could refer to either ‘Data.Aeson.allNullaryToStringTag’,
                             imported from ‘Data.Aeson’ at src/Data/Swagger/Internal/Schema.hs:35:1-17
                             (and originally defined in ‘aeson-1.2.2.0:Data.Aeson.Types.Internal’)
                          or ‘Data.Swagger.SchemaOptions.allNullaryToStringTag’,
                             imported from ‘Data.Swagger.SchemaOptions’ at src/Data/Swagger/Internal/Schema.hs:67:1-33
                             (and originally defined
                                at src/Data/Swagger/SchemaOptions.hs:19:5-25)
    |
741 |   | allNullaryToStringTag opts && allNullary = pure $ unnamed (toStringTag sumSchema)
    |     ^^^^^^^^^^^^^^^^^^^^^

src/Data/Swagger/Internal/Schema.hs:767:19: error:
    Ambiguous occurrence ‘constructorTagModifier’
    It could refer to either ‘Data.Aeson.constructorTagModifier’,
                             imported from ‘Data.Aeson’ at src/Data/Swagger/Internal/Schema.hs:35:1-17
                             (and originally defined in ‘aeson-1.2.2.0:Data.Aeson.Types.Internal’)
                          or ‘Data.Swagger.SchemaOptions.constructorTagModifier’,
                             imported from ‘Data.Swagger.SchemaOptions’ at src/Data/Swagger/Internal/Schema.hs:67:1-33
                             (and originally defined
                                at src/Data/Swagger/SchemaOptions.hs:14:5-26)
    |
767 |     tag = T.pack (constructorTagModifier opts (conName (Proxy3 :: Proxy3 c f p)))
    |                   ^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by fizruk** [comment]
@phadej I see you self-assigned this.
I'll wait for a fix before making a release then.

**Comment by phadej** [comment]
Fixed in #125

**Comment by fizruk** [comment]
Released in [`swagger2-2.1.6`](http://hackage.haskell.org/package/swagger2-2.1.6).
