### ISSUE TITLE
swagger2 2.9 doesn't compile with insert-ordered-containers < 0.3

### ISSUE THREAD

**Issue by arybczak** [GetShopTV/swagger2#265]
It fails with

```
[ 1 of 18] Compiling Data.HashMap.Strict.InsOrd.Compat ( src/Data/HashMap/Strict/InsOrd/Compat.hs, dist/build/Data/HashMap/Strict/InsOrd/Compat.o, dist/build/Data/HashMap/Strict/InsOrd/Compat.dyn_o )
src/Data/HashMap/Strict/InsOrd/Compat.hs:80:3: error: [GHC-87543]
    Ambiguous occurrence ‘null’.
    It could refer to
       either ‘Prelude.null’,
              imported from ‘Prelude’ at src/Data/HashMap/Strict/InsOrd/Compat.hs:74:8-40
              (and originally defined in ‘ghc-internal-9.1003.0:GHC.Internal.Data.Foldable’),
           or ‘Data.HashMap.Strict.InsOrd.null’,
              imported from ‘Data.HashMap.Strict.InsOrd’ at src/Data/HashMap/Strict/InsOrd/Compat.hs:140:1-33.
   |
80 |   null,
   |   ^^^^

src/Data/HashMap/Strict/InsOrd/Compat.hs:83:3: error: [GHC-87543]
    Ambiguous occurrence ‘lookup’.
    It could refer to
       either ‘Prelude.lookup’,
              imported from ‘Prelude’ at src/Data/HashMap/Strict/InsOrd/Compat.hs:74:8-40
              (and originally defined in ‘ghc-internal-9.1003.0:GHC.Internal.List’),
           or ‘Data.HashMap.Strict.InsOrd.lookup’,
              imported from ‘Data.HashMap.Strict.InsOrd’ at src/Data/HashMap/Strict/InsOrd/Compat.hs:140:1-33.
   |
83 |   lookup,
   |   ^^^^^^

src/Data/HashMap/Strict/InsOrd/Compat.hs:97:3: error: [GHC-87543]
    Ambiguous occurrence ‘map’.
    It could refer to
       either ‘Prelude.map’,
              imported from ‘Prelude’ at src/Data/HashMap/Strict/InsOrd/Compat.hs:74:8-40
              (and originally defined in ‘ghc-internal-9.1003.0:GHC.Internal.Base’),
           or ‘Data.HashMap.Strict.InsOrd.map’,
              imported from ‘Data.HashMap.Strict.InsOrd’ at src/Data/HashMap/Strict/InsOrd/Compat.hs:140:1-33.
   |
97 |   map,
   |   ^^^

src/Data/HashMap/Strict/InsOrd/Compat.hs:111:3: error: [GHC-87543]
    Ambiguous occurrence ‘foldl'’.
    It could refer to
       either ‘Prelude.foldl'’,
              imported from ‘Prelude’ at src/Data/HashMap/Strict/InsOrd/Compat.hs:74:8-40
              (and originally defined in ‘ghc-internal-9.1003.0:GHC.Internal.Data.Foldable’),
           or ‘Data.HashMap.Strict.InsOrd.foldl'’,
              imported from ‘Data.HashMap.Strict.InsOrd’ at src/Data/HashMap/Strict/InsOrd/Compat.hs:140:1-33.
    |
111 |   foldl',
    |   ^^^^^^

src/Data/HashMap/Strict/InsOrd/Compat.hs:113:3: error: [GHC-87543]
    Ambiguous occurrence ‘foldr’.
    It could refer to
       either ‘Prelude.foldr’,
              imported from ‘Prelude’ at src/Data/HashMap/Strict/InsOrd/Compat.hs:74:8-40
              (and originally defined in ‘ghc-internal-9.1003.0:GHC.Internal.Data.Foldable’),
           or ‘Data.HashMap.Strict.InsOrd.foldr’,
              imported from ‘Data.HashMap.Strict.InsOrd’ at src/Data/HashMap/Strict/InsOrd/Compat.hs:140:1-33.
    |
113 |   foldr,
    |   ^^^^^

src/Data/HashMap/Strict/InsOrd/Compat.hs:120:3: error: [GHC-87543]
    Ambiguous occurrence ‘filter’.
    It could refer to
       either ‘Prelude.filter’,
              imported from ‘Prelude’ at src/Data/HashMap/Strict/InsOrd/Compat.hs:74:8-40
              (and originally defined in ‘ghc-internal-9.1003.0:GHC.Internal.List’),
           or ‘Data.HashMap.Strict.InsOrd.filter’,
              imported from ‘Data.HashMap.Strict.InsOrd’ at src/Data/HashMap/Strict/InsOrd/Compat.hs:140:1-33.
    |
120 |   filter,
    |   ^^^^^^
```

because the [relevant branch](https://github.com/GetShopTV/swagger2/blob/614cc220745942f7adfc9d0e7b2ff0504494494a/src/Data/HashMap/Strict/InsOrd/Compat.hs#L139) doesn't hide Prelude imports.

**Comment by ysangkok** [comment]
@swamp-agr Have you seen this issue?

**Comment by swamp-agr** [comment]
Please find release on Hackage: https://hackage.haskell.org/package/swagger2-2.9.1
